apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- deployment.yaml
- ingress.yaml
namespace: staging
images:
  - name: marcoinacio/argo-combined-app
    newTag: "cfdc378f02a72ff04424921e47b66e562eb13051"
