apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- hpa.yaml
- istio.yaml
- rollout.yaml
namespace: production
images:
  - name: marcoinacio/argo-combined-app
    newTag: "v3.1.2"
